workflows:
  android-build-and-release:
    name: Android Build and Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_VERSION: "17"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Setup Java
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v $JAVA_VERSION)
          echo "Java set to version $JAVA_VERSION"
      - name: Grant execute permission to Gradle
        script: chmod +x gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug --stacktrace
      - name: Build Release APK
        script: ./gradlew assembleRelease --stacktrace
      - name: Prepare APK for Upload
        script: |
          mkdir -p artifacts
          cp app/build/outputs/apk/debug/app-debug.apk artifacts/Around-Egypt-debug.apk
          cp app/build/outputs/apk/release/app-release.apk artifacts/Around-Egypt-release.apk
    artifacts:
      - artifacts/Around-Egypt-debug.apk
      - artifacts/Around-Egypt-release.apk
    publishing:
      email:
        recipients:
          - ae38988@gmail.com
      github:
        tag: v1.0.$BUILD_NUMBER
        release_name: Release v1.0.$BUILD_NUMBER
        assets:
          - artifacts/Around-Egypt-release.apk
          - artifacts/Around-Egypt-debug.apk
