name: Android Build and Release

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: ['debug', 'release']
      fail-fast: false
      max-parallel: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble${{ matrix.build-type }} --stacktrace

      - name: Run Unit Tests
        run: ./gradlew test${{ matrix.build-type }}UnitTest --stacktrace

      - name: Prepare APK for Upload
        run: |
          # Copy APK to root directory and rename
          cp app/build/outputs/apk/${{ matrix.build-type }}/app-${{ matrix.build-type }}.apk Around-Egypt-${{ matrix.build-type }}.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Around-Egypt-${{ matrix.build-type }}.apk
          path: Around-Egypt-${{ matrix.build-type }}.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten Artifact Directories
        run: |
          # Move all APKs from subdirectories to the root artifacts directory
          find artifacts -name '*.apk' -exec mv {} artifacts \;

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release APK (Release Build)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Around-Egypt-release.apk
          asset_name: Around-Egypt-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Debug APK (Optional)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Around-Egypt-debug.apk
          asset_name: Around-Egypt-debug.apk
          asset_content_type: application/vnd.android.package-archive